src/plugins/oauth2_qq/__init__.py
# -*- coding: utf-8 -*-
"""
    passport.plugins.oauth2_qq
    ~~~~~~~~~~~~~~

    使用qq登录

    :copyright: (c) 2017 by staugur.
    :license: MIT, see LICENSE for more details.
"""

#: Importing these two modules is the first and must be done.
#: 首先导入这两个必须模块
from __future__ import absolute_import
from libs.base import PluginBase
#: Import the other modules here, and if it's your own module, use the relative Import. eg: from .lib import Lib
#: 在这里导入其他模块, 如果有自定义包目录, 使用相对导入, 如: from .lib import Lib
import json
from flask import Blueprint, request, jsonify, g, flash, redirect, url_for
from utils.web import OAuth2, dfr, oauth2_name2type, checkGet_ssoRequest, oauth2_genderconverter
from config import PLUGINS
from libs.auth import Authentication

#：Your plug-in name must be consistent with the plug-in directory name.
#：你的插件名称，必须和插件目录名称等保持一致.
__plugin_name__ = "oauth2_qq"
#: Plugin describes information. What does it do?
#: 插件描述信息,什么用处.
__description__ = "Connection QQ with OAuth2"
#: Plugin Author
#: 插件作者
__author__      = "Mr.tao <staugur@saintic.com>"
#: Plugin Version
#: 插件版本
__version__     = "0.1.0"
#: Plugin Url
#: 插件主页
__url__         = "https://www.saintic.com"
#: Plugin License
#: 插件许可证
__license__     = "MIT"
#: Plugin License File
#: 插件许可证文件
__license_file__= "LICENSE"
#: Plugin Readme File
#: 插件自述文件
__readme_file__ = "README"
#: Plugin state, enabled or disabled, default: enabled
#: 插件状态, enabled、disabled, 默认enabled
name = "qq"
if PLUGINS[name]["ENABLE"] in ("true", "True", True):
    __state__   = "enabled"
else:
    __state__   = "disabled"

qq = OAuth2(name,
    client_id = PLUGINS[name]["APP_ID"],
    client_secret = PLUGINS[name]["APP_KEY"],
    redirect_url = PLUGINS[name]["REDIRECT_URI"],
    authorize_url = "https://graph.qq.com/oauth2.0/authorize",
    access_token_url = "https://graph.qq.com/oauth2.0/token",
    access_token_method = "get",
    get_openid_url = "https://graph.qq.com/oauth2.0/me",
    get_openid_method = "get",
    get_userinfo_url = "https://graph.qq.com/user/get_user_info",
    get_userinfo_method = "get"
)

plugin_blueprint = Blueprint("oauth2_qq", "oauth2_qq")
@plugin_blueprint.route("/login")
def login():
    """ 跳转此OAuth应用登录以授权
    此路由地址：/oauth2/qq/login
    """
    return qq.authorize()

@plugin_blueprint.route("/authorized")
def authorized():
    """ 授权回调路由
    此路由地址：/oauth2/qq/authorized
    """
    # 加密的sso参数值
    sso = request.args.get("sso") or None
    # 换取access_token
    resp = qq.authorized_response()
    if "callback" in resp:
        resp = json.loads(resp[10:-3])
    else:
        resp = qq.url_code(resp)
    if resp and isinstance(resp, dict) and "access_token" in resp:
        # 获取用户唯一标识
        openid = json.loads(qq.get_openid(resp["access_token"])[10:-3]).get("openid")
        # 根据access_token获取用户基本信息
        user = qq.get_userinfo(resp["access_token"], openid=openid, oauth_consumer_key=PLUGINS[name]["APP_ID"])
        if int(user.get("ret", 0)) < 0:
            flash(user.get("msg"))
            return redirect(g.redirect_uri)
        # 处理第三方登录逻辑
        auth = Authentication(g.mysql, g.redis)
        # 第三方账号登录入口`oauth2_go`
        goinfo = auth.oauth2_go(name=name, signin=g.signin, tokeninfo=resp, userinfo=dict(openid=openid, nick_name=user["nickname"], gender=oauth2_genderconverter(user["gender"]), avatar=user["figureurl_qq_2"] or user["figureurl_qq_1"], location="%s %s" %(user.get("province"), user.get("city"))), uid=g.uid)
        goinfo = dfr(goinfo)
        if goinfo["pageAction"] == "goto_signIn":
            """ 未登录流程->已经绑定过账号，需要设置登录态 """
            uid = goinfo["goto_signIn_data"]["guid"]
            # 记录登录日志
            auth.brush_loginlog(dict(identity_type=oauth2_name2type(name), uid=uid, success=True), login_ip=g.ip, user_agent=request.headers.get("User-Agent"))
            # 设置登录态
            return qq.goto_signIn(uid=uid, sso=sso)
        elif goinfo["pageAction"] == "goto_signUp":
            """ 未登录流程->openid没有对应账号，执行注册或绑定功能 """
            return qq.goto_signUp(openid=goinfo["goto_signUp_data"]["openid"], sso=sso)
        else:
            # 已登录流程->正在绑定第三方账号：反馈绑定结果
            if goinfo["success"]:
                # 绑定成功，返回原页面
                flash(u"已绑定")
            else:
                # 绑定失败，返回原页面
                flash(goinfo["msg"])
            # 跳回绑定设置页面
            return redirect(url_for("front.userset", _anchor="bind"))
    else:
        flash(u'Access denied: reason=%s error=%s' % (
            resp.get('error'),
            resp.get('error_description')
        ))
    return redirect(g.redirect_uri)

#: 返回插件主类
def getPluginClass():
    return OAuth2_QQ_Main

#: 插件主类, 不强制要求名称与插件名一致, 保证getPluginClass准确返回此类
class OAuth2_QQ_Main(PluginBase):
    """ 继承自PluginBase基类 """

    def register_tep(self):
        """注册模板入口, 返回扩展点名称及扩展的代码, 其中include点必须是实际的HTML文件, string点必须是HTML代码."""
        tep = {"auth_signIn_socialLogin_include": "connect_qq.html"}
        return tep

    def register_bep(self):
        """注册蓝图入口, 返回蓝图路由前缀及蓝图名称"""
        bep = {"prefix": "/oauth2/qq", "blueprint": plugin_blueprint}
        return bep


def register():
    om = OAuth2_QQ_Main()
    return dict(
        tep=om.register_tep(),
        bep=om.register_bep(),
    )

src/views/FrontView.py
# -*- coding: utf-8 -*-
"""
    passport.views.FrontView
    ~~~~~~~~~~~~~~

    The blueprint for front view.

    :copyright: (c) 2017 by staugur.
    :license: MIT, see LICENSE for more details.
"""
from config import SYSTEM
from utils.web import login_required, anonymous_required, adminlogin_required, dfr, oauth2_name2type, get_redirect_url, checkGet_ssoRequest, checkSet_ssoTicketSid, set_redirectLoginstate, set_jsonifyLoginstate, FastPushMessage
from utils.tool import logger, email_check, phone_check, md5
from libs.auth import Authentication
from urllib import urlencode
from flask import Blueprint, request, render_template, g, redirect, url_for, flash, make_response, jsonify

#初始化前台蓝图
FrontBlueprint = Blueprint("front", __name__)

@FrontBlueprint.route('/')
@login_required
def index():
    # 未登录时跳转到登录页；已登录后跳转到个人设置页面
    return redirect(url_for(".userset"))

@FrontBlueprint.route('/user/setting/')
@login_required
def userset():
    """用户基本设置"""
    Action = request.args.get("Action")
    if Action == "bindLauth":
        # 绑定
        return render_template("user/user.bind.html")
    return render_template("user/setting.html")

@FrontBlueprint.route('/user/app/')
@adminlogin_required
def userapp():
    Action = request.args.get("Action")
    if Action == "editView":
        # 编辑应用
        return render_template("user/apps.edit.html")
    # 默认返回应用选项卡
    return render_template("user/apps.html")

@FrontBlueprint.route('/sys/manager/')
@adminlogin_required
def sysmanager():
    # 系统管理
    return render_template("user/sysmanager.html")

@FrontBlueprint.route('/user/message/')
@login_required
def usermsg():
    """用户消息"""
    return render_template("user/message.html")

@FrontBlueprint.route('/user/security/')
@login_required
def usersecurity():
    """用户安全"""
    return render_template("user/security.html")

@FrontBlueprint.route('/signUp', methods=['GET', 'POST'])
@anonymous_required
def signUp():
    if request.method == 'POST':
        res = dict(msg=None, code=1, nextUrl=url_for('.signUp'))
        if True:
            account = request.form.get("account")
            vcode = request.form.get("vcode")
            password = request.form.get("password")
            repassword = request.form.get("repassword")
            auth = Authentication(g.mysql, g.redis)
            result = auth.signUp(account=account, vcode=vcode, password=password, repassword=repassword, register_ip=g.ip)
            #注册欢迎消息
            FastPushMessage(result, "欢迎您的加入！%s使用中有任何问题，都可以反馈哦。" %("" if email_check(account) else "您使用手机注册，已经完成实名认证！", ))
            if result["success"]:
                res.update(code=0, nextUrl=url_for('.signIn'))
            else:
                res.update(msg=result["msg"])
        else:
            res.update(msg="Man-machine verification failed")
        return jsonify(dfr(res))
    return render_template("auth/signUp.html")

@FrontBlueprint.route('/signIn', methods=['GET', 'POST'])
def signIn():
    """ 单点登录流程
        1. Client跳转到Server的登录页，携带参数sso(所需sso信息的加密串)，验证并获取应用数据。
        2. 未登录时，GET请求显示登录表单，输入用户名密码或第三方POST登录成功后(一处是signIn post；一处是OAuthDirectLogin post；一处是OAuthBindAccount post)，创建全局会话(设置Server登录态)、授权令牌ticket，根据ticket生成sid(全局会话id)写入redis，ReturnUrl组合ticket跳转；
           已登录后，检查是否有sid，没有则创建ticket，ReturnUrl组合ticket跳转。
        3. 校验参数通过后，设置ReturnUrl(从数据库读取)为Client登录地址；校验未通过时ReturnUrl为系统redirect_uri。
        4. Client用ticket到Server校验(通过api方式)，通过redis校验cookie是否存在；存在则创建局部会话(设置Client登录态)，否则登录失败。
        -- sso加密规则：
            aes_cbc(jwt_encrypt("app_name:app_id.app_secret"))
        -- sso校验流程：
            根据sso参数，验证是否有效，解析参数获取name、id、secret等，并用name获取到对应信息一一校验
        -- 备注：
            第3步，需要signIn、OAuthGuide方面路由设置
            第4步，需要在插件内增加api路由
    """
    # 加密的sso参数值
    sso = request.args.get("sso") or None
    sso_isOk, sso_returnUrl, sso_appName = checkGet_ssoRequest(sso)
    logger.debug("method: {}, sso_isOk: {}, ReturnUrl: {}".format(request.method, sso_isOk, sso_returnUrl))
    if g.signin:
        # 已登录后流程
        # 如果没有sid说明是本地登录，需要重置登录态
        if sso_isOk:
            if g.sid:
                # 创建ticket，返回为真即是ticket
                tickets = g.api.usersso.ssoCreateTicket(sid=g.sid, agent=g.agent, ip=g.ip)
                if tickets:
                    ticket, sid = tickets
                    returnUrl = "{}&ticket={}".format(sso_returnUrl, ticket)
                    return redirect(returnUrl)
                else:
                    flash(dfr(dict(msg="Failed to create authorization ticket")))
            else:
                sessionId, returnUrl = checkSet_ssoTicketSid(sso_isOk, sso_returnUrl, sso_appName, g.uid, get_redirect_url("front.userset"))
                return set_redirectLoginstate(sessionId, returnUrl)
        return redirect(url_for("front.userset"))
    else:
        # 未登录时流程
        if request.method == 'POST':
            # POST请求不仅要设置登录态、还要设置全局会话
            res = dict(msg=None, code=1, nextUrl=url_for('.signIn', sso=sso) if sso_isOk else url_for('.signIn'))
            if True:
                auth = Authentication(g.mysql, g.redis)
                result = auth.signIn(account=request.form.get("account"), password=request.form.get("password"))
                if result["success"]:
                    # 记录登录日志
                    auth.brush_loginlog(result, login_ip=g.ip, user_agent=g.agent)
                    sessionId, returnUrl = checkSet_ssoTicketSid(sso_isOk, sso_returnUrl, sso_appName, result["uid"], get_redirect_url("front.userset"))
                    logger.debug("signIn post returnUrl: {}".format(returnUrl))
                    res.update(nextUrl=returnUrl, code=0)
                    return set_jsonifyLoginstate(sessionId, dfr(res))
                    #return set_redirectLoginstate(sessionId, returnUrl)
                else:
                    res.update(msg=result["msg"])
            else:
                res.update(msg="Man-machine verification failed")
            return jsonify(dfr(res))
            #return redirect(url_for('.signIn', sso=sso)) if sso_isOk else redirect(url_for('.signIn'))
        else:
            # GET请求仅用于渲染
            return render_template("auth/signIn.html")

@FrontBlueprint.route("/OAuthGuide", methods=["GET", "POST"])
@anonymous_required
def OAuthGuide():
    """OAuth2登录未注册时引导路由(来源于OAuth goto_signUp)，选择绑定已有账号或直接登录(首选)"""
    if request.method == 'POST':
        Action = request.args.get("Action")
        sso = request.args.get("sso") or None
        logger.debug("OAuthGuide, sso type: {}, content: {}".format(type(sso), sso))
        res = dict(msg=None, code=1)
        if Action == "bindLogin":
            if True:
                auth = Authentication()
                result = auth.oauth2_bindLogin(openid=request.form.get("openid"), account=request.form.get("account"), password=request.form.get("password"))
                if result["success"]:
                    # 记录登录日志
                    auth.brush_loginlog(result, login_ip=g.ip, user_agent=g.agent)
                    sso_isOk, sso_returnUrl, sso_appName = checkGet_ssoRequest(sso)
                    sessionId, returnUrl = checkSet_ssoTicketSid(sso_isOk, sso_returnUrl, sso_appName, result["uid"], url_for("front.userset", _anchor="bind"))
                    logger.debug("OAuthGuide bindLogin post returnUrl: {}".format(returnUrl))
                    res.update(nextUrl=returnUrl, code=0)
                    return set_jsonifyLoginstate(sessionId, dfr(res))
                    #return set_redirectLoginstate(sessionId, returnUrl)
                else:
                    res.update(msg=result["msg"])
            else:
                res.update(msg="Man-machine verification failed")
            return jsonify(dfr(res))
            #return redirect(url_for('.OAuthBindAccount', openid=openid, sso=sso))
        elif Action == "directLogin":
            auth = Authentication()
            # 直接注册新账号并设置登录态
            result = auth.oauth2_signUp(request.form.get("openid"), g.ip)
            if result["success"]:
                # 记录登录日志
                auth.brush_loginlog(result, login_ip=g.ip, user_agent=request.headers.get("User-Agent"))
                sso_isOk, sso_returnUrl, sso_appName = checkGet_ssoRequest(sso)
                sessionId, returnUrl = checkSet_ssoTicketSid(sso_isOk, sso_returnUrl, sso_appName, result["uid"], url_for("front.userset", _anchor="bind"))
                logger.debug("OAuthGuide directLogin post returnUrl: {}".format(returnUrl))
                res.update(nextUrl=returnUrl, code=0)
                return set_jsonifyLoginstate(sessionId, dfr(res))
                #return set_redirectLoginstate(sessionId, returnUrl)
            else:
                res.update(msg=result["msg"])
            return jsonify(dfr(res))
            #return redirect(url_for("front.OAuthGuide", openid=openid, sso=sso))
    else:
        if request.args.get("openid"):
            return render_template("auth/OAuthGuide.html")
        else:
            return redirect(g.redirect_uri)

@FrontBlueprint.route("/signOut")
@login_required
def signOut():
    """ 单点注销流程
        1. 根据sid查找注册的clients
        2. pop一个client并跳转到其注销页面，携带参数为`NextUrl=当前路由地址`，如果有`ReturnUrl`同样携带。
           client处理：检测通过注销局部会话并跳转回当前路由
        3. 循环第2步，直到clients为空（所有已注册的局部会话已经注销）
        4. 注销本地全局会话，删除相关数据，跳转到登录页面
    """
    # 最终跳转回地址
    ReturnUrl = request.args.get("ReturnUrl") or url_for(".signOut", _external=True)
    if g.sid:
        clients = g.api.usersso.ssoGetRegisteredClient(g.sid)
        logger.debug("has sid, get clients: {}".format(clients))
        if clients and isinstance(clients, list) and len(clients) > 0:
            clientName = clients.pop()
            clientData = g.api.userapp.getUserApp(clientName)
            if clientData:
                if g.api.usersso.clearRegisteredClient(g.sid, clientName):

src/templates/user/apps.edit.html
{% extends "user/micro.html" %}

{% block container %}
            <div class="layui-row">
               <div class="layui-col-md12">
                   <form class="layui-form layui-form-pane" action="">
                        <div class="layui-form-item">
                            <label class="layui-form-label">名称</label>
                            <div class="layui-input-block">
                                <input type="text" name="name" autocomplete="off" placeholder="应用标识名称，请以英文格式书写" class="layui-input layui-disabled" value="" lay-verify="name" id="name" disabled="disabled">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">描述</label>
                            <div class="layui-input-block">
                                <input type="text" name="description" autocomplete="off" placeholder="应用作用描述" class="layui-input" value="" lay-verify="required" id="description">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">回调域名</label>
                            <div class="layui-input-block">
                                <input type="text" name="app_redirect_url" autocomplete="off" placeholder="应用回调根地址，请书写完全合格域名" class="layui-input" value="" lay-verify="required|url" id="app_redirect_url">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <button class="layui-btn layui-btn-fluid" lay-submit="" lay-filter="editApp">点击修改</button>
                        </div>
                    </form>
                </div>
            </div>
{% endblock %}

{% block script %}
<script type="text/javascript">
layui.use(["form", "layer", "util"], function(){
    var form = layui.form, layer = layui.layer, $ = layui.jquery;
    //表单自定义校验
    form.verify({
        name: function(value, item){ //value：表单的值、item：表单的DOM对象
            if(!new RegExp("^[a-zA-Z0-9_\\s·]+$").test(value)){
                return '应用名不能有特殊字符';
            }
            if(/(^\_)|(\__)|(\_+$)/.test(value)){
                return '应用名首尾不能出现下划线\'_\'';
            }
            if(/^\d+\d+\d$/.test(value)){
                return '应用名不能全为数字';
            }
        }
    });
    //监听编辑应用提交
    form.on('submit(editApp)', function(data){
        field = data.field; //当前容器的全部表单字段，键值对形式：{name: value}
        $.ajax({
            url: "{{ url_for('api.userapp') }}",
            method: "PUT",
            data: field,
            success: function(res) {
                console.log(res);
                if (res.code==0) {
                    layer.msg("已修改应用");
                    //更新隐藏域输入框的值
                    parent.document.getElementById("editView").value = JSON.stringify(field);
                    //得到当前iframe层的索引
                    var index = parent.layer.getFrameIndex(window.name);
                    //再执行关闭
                    parent.layer.close(index); 
                } else {
                    layer.msg(res.msg);
                }
            },
            error: function(error){
                layer.msg("服务器异常！");
            }
        });
        return false; //阻止表单跳转。如果需要表单跳转，去掉这段即可。
    });
});
</script>
{% endblock %}

src/templates/user/apps.html
{% extends "user/base.html" %}

{% block title %}应用管理{% endblock %}

{% block userpanel %}
    <div class="fly-panel fly-panel-user" pad20>
        <div class="layui-tab layui-tab-brief" lay-filter="appList">
            <ul class="layui-tab-title">
                <li class="layui-this" lay-id="appList">应用列表</li>
                <li lay-id="newApp">新建应用</li>
            </ul>
            <div class="layui-tab-content" style="height: 100px;">
                <div class="layui-tab-item layui-show">
                    <table id="userapps" lay-filter="userAppTable"></table>
                </div>
                <div class="layui-tab-item">
                    <form class="layui-form layui-form-pane" action="">
                        <div class="layui-form-item">
                            <label class="layui-form-label">名称</label>
                            <div class="layui-input-block">
                                <input type="text" name="name" autocomplete="off" placeholder="应用标识名称，请以英文格式书写" class="layui-input" value="" lay-verify="required|name">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">描述</label>
                            <div class="layui-input-block">
                                <input type="text" name="description" autocomplete="off" placeholder="应用作用描述" class="layui-input" value="" lay-verify="required">
                            </div>
                        </div>
                        <div class="layui-form-item">
                            <label class="layui-form-label">回调域名</label>
                            <div class="layui-input-block">
                                <input type="text" name="app_redirect_url" autocomplete="off" placeholder="应用回调根地址，请书写完全合格域名" class="layui-input" value="" lay-verify="required|url">
                            </div>
                        </div>
                        <input type="hidden" id="editView">
                        <div class="layui-form-item">
                            <button class="layui-btn" lay-submit="" lay-filter="newApp" id="newAppSubmit">点击提交</button>
                        </div>
                    </form>
                </div>
            </div>
        </div> 
    </div>
{% endblock %}

{% block script %}
<script type="text/html" id="userAppBar">
    <a class="layui-btn layui-btn-xs layui-btn-primary" lay-event="detail">查看</a>
    <a class="layui-btn layui-btn-xs" lay-event="edit">编辑</a>
    <a class="layui-btn layui-btn-xs layui-btn-danger" lay-event="del">删除</a>
</script>
<script type="text/javascript">
    layui.use("app");
</script>
{% endblock %}

src/templates/user/base.html
{% extends "public/base.html" %}

{% block baseTitle %}
    {% block title %}{% endblock %} - SaintIC Passport
{% endblock %}

{% block baseHead %}
    <link rel="stylesheet" href="/static/css/global.css">
    {% block head %}{% endblock %}
{% endblock %}

{% block baseHtml %}
<!--顶部导航-->
<div class="fly-header layui-bg-black">
    <div class="layui-container">
        <a class="fly-logo" href="/"><img src="/static/images/logo.png" alt="Passport"></a>
        {% if g.signin %}
        <ul class="layui-nav fly-nav-user">
            <li class="layui-nav-item">
                <a class="fly-nav-avatar" href="javascript:;">
                    <cite class="layui-hide-xs" id="nav_nickname"></cite>
                    <!--
                    <i class="iconfont icon-renzheng layui-hide-xs" title="已实名、未实名"></i>
                    <i class="layui-badge fly-badge-vip layui-hide-xs">VIP3</i>
                    -->
                    <img id="nav_avatar" src="https://img.saintic.com/cdn/images/defaultAvatar.png">
                </a>
                <dl class="layui-nav-child">
                    <dd><a href="{{ url_for('front.userset') }}"><i class="saintic-icon saintic-icon-setting"></i>基本设置</a></dd>
                    <dd><a href="{{ url_for('front.usersecurity') }}"><i class="saintic-icon saintic-icon-security"></i>账号安全</a></dd>
                    <dd><a href="{{ url_for('front.usermsg') }}"><i class="saintic-icon saintic-icon-message"></i>我的消息</a></dd>
                    <hr style="margin: 5px 0;">
                    <dd><a href="{{ url_for('front.signOut') }}"><i class="saintic-icon saintic-icon-logout"></i>注销登录</a></dd>
                </dl>
            </li>
        </ul>
        {% endif %}
    </div>
</div>

<div class="layui-container fly-marginTop fly-user-main">
    {% block leftNav %}
    <!--左侧垂直导航-->
    <ul class="layui-nav layui-nav-tree layui-inline" lay-filter="user">
        <li class="layui-nav-item {% if request.endpoint == 'front.userset' %}layui-this{% endif %}">
            <a href="{{ url_for('front.userset') }}"><i class="saintic-icon saintic-icon-setting"></i>&nbsp;&nbsp;基本设置</a>
        </li>
        <li class="layui-nav-item {% if request.endpoint == 'front.usersecurity' %}layui-this{% endif %}">
            <a href="{{ url_for('front.usersecurity') }}"><i class="saintic-icon saintic-icon-security"></i>&nbsp;&nbsp;账号安全</a>
        </li>
        <li class="layui-nav-item {% if request.endpoint == 'front.usermsg' %}layui-this{% endif %}">
            <a href="{{ url_for('front.usermsg') }}"><i class="saintic-icon saintic-icon-message"></i>&nbsp;&nbsp;我的消息</a>
        </li>
        {% if tpl_adminlogin_required() %}
        <!--
        <li class="layui-nav-item {% if request.endpoint == 'front.sysmanager' %}layui-this{% endif %}">
            <a href="{{ url_for('front.sysmanager') }}"><i class="saintic-icon saintic-icon-system-setting"></i>&nbsp;&nbsp;系统管理</a>
        </li>
        -->
        <li class="layui-nav-item {% if request.endpoint == 'front.userapp' %}layui-this{% endif %}">
            <a href="{{ url_for('front.userapp') }}"><i class="saintic-icon saintic-icon-app-management"></i>&nbsp;&nbsp;应用管理</a>
        </li>
        {% endif %}
    </ul>
    <!--移动端适应按钮-->
    <div class="site-tree-mobile layui-hide">
        <i class="layui-icon">&#xe602;</i>
    </div>
    <div class="site-mobile-shade"></div>
    <div class="site-tree-mobile layui-hide">
        <i class="layui-icon">&#xe602;</i>
    </div>
    <div class="site-mobile-shade"></div>
    {% endblock %}
    <!--主要内容-->
    {% block userpanel %}{% endblock %}
</div>

{% include "public/footer.html" %}
{% endblock baseHtml %}

{% block baseScript %}
    {% block script %}{% endblock %}
{% endblock baseScript %}

src/templates/user/message.html
{% extends "user/base.html" %}

{% block title %}我的消息{% endblock %}

{% block userpanel %}
<div class="fly-panel fly-panel-user" pad20>
    <div class="layui-tab layui-tab-brief" lay-filter="user" id="LAY_msg" style="margin-top: 15px;">
        {%- set status = request.args.status or 1 %}
        {%- if status in (1, '1') %}
        <a href="{{ url_for('front.usermsg', status=0) }}"><button class="layui-btn layui-btn-normal">查看已读消息</button></a>
        {%- elif status in (0, '0') %}
        <a href="{{ url_for('front.usermsg', status=1) }}"><button class="layui-btn layui-btn-normal">查看未读消息</button></a>
        {%- else %}
        <a href="{{ url_for('front.usermsg', status=0) }}"><button class="layui-btn layui-btn-normal">查看已读消息</button></a>
        <a href="{{ url_for('front.usermsg', status=1) }}"><button class="layui-btn layui-btn-normal">查看未读消息</button></a>
        {%- endif %}
        <button class="layui-btn layui-btn-danger layui-hide" id="LAY_delallmsg">清空全部消息</button>
        <div id="LAY_minemsg" style="margin-top: 10px;"></div>
    </div>
</div>
{% endblock %}

{% block script %}
<script type="text/javascript">
    layui.use("message");
</script>
{% endblock %}

src/templates/user/micro.html
{% extends "public/base.html" %}

{% block baseTitle %}
    {% block title %}{% endblock %} - SaintIC Passport
{% endblock %}

{% block baseHead %}
    {% block head %}{% endblock %}
    {% block resethtmlbody %}
    <style type="text/css">
        html,body{overflow-x: hidden;}
        html body{margin-top: 18px;}
    </style>
    {%- endblock %}
{% endblock %}

{% block baseHtml %}
    {% block topNav %}{% endblock %}
    <div class="layui-container">
        {% block container %}{% endblock %}
    </div>
{% endblock baseHtml %}

{% block baseScript %}
    {% block script %}{% endblock %}
{% endblock baseScript %}

src/templates/user/user.html
{% extends "user/base.html" %}

{% block title %}用户管理{% endblock %}